const KEY_PECES='stockPeces'; const KEY_PERSONAS='stockPersonas';
let peces=JSON.parse(localStorage.getItem(KEY_PECES)||'[]'); let personas=JSON.parse(localStorage.getItem(KEY_PERSONAS)||'[]');
const $=id=>document.getElementById(id); const hoy=new Date().toISOString().slice(0,10); $('fechaIngreso').value=hoy;
function guardar(){localStorage.setItem(KEY_PECES,JSON.stringify(peces));localStorage.setItem(KEY_PERSONAS,JSON.stringify(personas));actualizar()}
function escapar(t=''){return t.replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function actualizar(){actualizarResumen(); cargarPersonasSelect(); renderPeces(); renderPersonas(); renderEntregas()}
function actualizarResumen(){$('totalPeces').textContent=peces.length;$('disponibles').textContent=peces.filter(p=>p.estado==='Disponible').length;$('entregados').textContent=peces.filter(p=>p.estado==='Entregado').length;$('totalPersonas').textContent=personas.length}
function cargarPersonasSelect(){const actual=$('personaId').value;$('personaId').innerHTML='<option value="">Sin asignar</option>'+personas.map(p=>`<option value="${p.id}">${escapar(p.nombre)}</option>`).join('');$('personaId').value=actual}
function imagenPez(p){if(p.imagen)return p.imagen;const s=(p.denominacion||'').toLowerCase();if(s.includes('payaso'))return 'img/pez-payaso.svg';if(s.includes('betta'))return 'img/pez-betta.svg';if(s.includes('guppy'))return 'img/pez-guppy.svg';return 'img/pez-generico.svg'}
function renderPeces(){const q=$('buscarPez').value.toLowerCase();const origen=$('filtrarOrigen').value;const lista=peces.filter(p=>(!q||`${p.denominacion} ${p.descripcion}`.toLowerCase().includes(q))&&(!origen||p.origen===origen));$('contadorPeces').textContent=`${lista.length} registro${lista.length!==1?'s':''}`;$('listaPeces').innerHTML=lista.length?lista.map(p=>{const persona=personas.find(x=>x.id===p.personaId);let clase=p.estado==='Entregado'?'entregado':p.estado==='Fallecido'?'fallecido':p.estado==='En observación'?'observacion':'';return `<article class="tarjeta"><img src="${imagenPez(p)}" alt="${escapar(p.denominacion)}"><div class="tarjeta-cuerpo"><h3>${escapar(p.denominacion)}</h3><span class="estado ${clase}">${escapar(p.estado)}</span><div class="meta"><b>Origen:</b> ${escapar(p.origen)}</div><div class="meta"><b>Ingreso:</b> ${p.fechaIngreso||'-'}</div><div class="meta">${escapar(p.descripcion||'Sin descripción')}</div>${persona?`<div class="meta"><b>Recibe:</b> ${escapar(persona.nombre)}</div>`:''}${p.fechaEntrega?`<div class="meta"><b>Entrega:</b> ${p.fechaEntrega}</div>`:''}<div class="card-acciones"><button class="editar" onclick="editarPez('${p.id}')">Editar</button><button class="eliminar" onclick="eliminarPez('${p.id}')">Eliminar</button></div></div></article>`}).join(''):'<div class="vacio">No se encontraron peces.</div>'}
function editarPez(id){const p=peces.find(x=>x.id===id);if(!p)return;$('pezId').value=p.id;$('denominacion').value=p.denominacion;$('descripcion').value=p.descripcion;$('origen').value=p.origen;$('fechaIngreso').value=p.fechaIngreso;$('fechaEntrega').value=p.fechaEntrega||'';$('personaId').value=p.personaId||'';$('estado').value=p.estado;$('vistaImagenPez').src=imagenPez(p);$('imagenPez').value='';window.scrollTo({top:0,behavior:'smooth'})}
function eliminarPez(id){if(confirm('¿Eliminar este registro?')){peces=peces.filter(p=>p.id!==id);guardar()}}
$('imagenPez').addEventListener('change',e=>{const archivo=e.target.files[0];if(!archivo)return;if(!archivo.type.startsWith('image/')){alert('Seleccioná un archivo de imagen.');e.target.value='';return}if(archivo.size>2*1024*1024){alert('La imagen supera los 2 MB. Elegí una imagen más pequeña.');e.target.value='';return}const lector=new FileReader();lector.onload=()=>{$('vistaImagenPez').src=lector.result};lector.readAsDataURL(archivo)});
$('quitarImagen').onclick=()=>{$('imagenPez').value='';$('vistaImagenPez').src='img/pez-generico.svg';$('vistaImagenPez').dataset.quitar='true'};
$('formPez').addEventListener('submit',e=>{e.preventDefault();const id=$('pezId').value;const anterior=id?peces.find(x=>x.id===id):null;const archivo=$('imagenPez').files[0];const guardarPez=imagen=>{const p={id:id||crypto.randomUUID(),denominacion:$('denominacion').value.trim(),descripcion:$('descripcion').value.trim(),origen:$('origen').value,fechaIngreso:$('fechaIngreso').value,fechaEntrega:$('fechaEntrega').value,personaId:$('personaId').value,estado:$('estado').value,imagen:imagen||null};if(p.personaId)p.estado='Entregado';if(id){const i=peces.findIndex(x=>x.id===id);peces[i]=p}else peces.push(p);guardar();e.target.reset();$('pezId').value='';$('fechaIngreso').value=hoy;$('vistaImagenPez').src='img/pez-generico.svg';$('vistaImagenPez').dataset.quitar='';};
if($('vistaImagenPez').dataset.quitar==='true')return guardarPez(null);
if(archivo){const lector=new FileReader();lector.onload=()=>guardarPez(lector.result);lector.readAsDataURL(archivo)}else guardarPez(anterior?.imagen||null)});
$('cancelarEdicion').onclick=()=>{$('formPez').reset();$('pezId').value='';$('fechaIngreso').value=hoy;$('vistaImagenPez').src='img/pez-generico.svg';$('vistaImagenPez').dataset.quitar=''};
$('formPersona').addEventListener('submit',e=>{e.preventDefault();const id=$('personaEditarId').value;const p={id:id||crypto.randomUUID(),nombre:$('nombrePersona').value.trim(),telefono:$('telefonoPersona').value.trim(),observaciones:$('observacionesPersona').value.trim()};if(id){const i=personas.findIndex(x=>x.id===id);personas[i]=p}else personas.push(p);guardar();e.target.reset();$('personaEditarId').value=''});
$('cancelarPersona').onclick=()=>{$('formPersona').reset();$('personaEditarId').value=''};
function renderPersonas(){$('listaPersonas').innerHTML=personas.length?personas.map(p=>{const cantidad=peces.filter(x=>x.personaId===p.id).length;return `<div class="persona"><div><h3>${escapar(p.nombre)}</h3><div class="meta">Tel.: ${escapar(p.telefono||'-')} · ${cantidad} pez${cantidad!==1?'ces':''}</div><div class="meta">${escapar(p.observaciones||'')}</div></div><div class="card-acciones"><button class="editar" onclick="editarPersona('${p.id}')">Editar</button><button class="eliminar" onclick="eliminarPersona('${p.id}')">Eliminar</button></div></div>`}).join(''):'<div class="vacio">Todavía no hay personas registradas.</div>'}
function editarPersona(id){const p=personas.find(x=>x.id===id);$('personaEditarId').value=p.id;$('nombrePersona').value=p.nombre;$('telefonoPersona').value=p.telefono||'';$('observacionesPersona').value=p.observaciones||'';window.scrollTo({top:0,behavior:'smooth'})}
function eliminarPersona(id){if(peces.some(p=>p.personaId===id)){alert('No se puede eliminar: la persona tiene peces asignados.');return}if(confirm('¿Eliminar esta persona?')){personas=personas.filter(p=>p.id!==id);guardar()}}
function renderEntregas(){const entregados=peces.filter(p=>p.personaId);$('listaEntregas').innerHTML=entregados.length?`<table class="tabla-entregas"><thead><tr><th>Persona</th><th>Pez</th><th>Origen</th><th>Entrega</th><th>Estado</th></tr></thead><tbody>${entregados.map(p=>{const per=personas.find(x=>x.id===p.personaId);return `<tr><td>${escapar(per?.nombre||'Sin datos')}</td><td>${escapar(p.denominacion)}</td><td>${escapar(p.origen)}</td><td>${p.fechaEntrega||'-'}</td><td>${escapar(p.estado)}</td></tr>`}).join('')}</tbody></table>`:'<div class="vacio">No hay peces entregados o asignados.</div>'}
document.querySelectorAll('.tab').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('activa'));document.querySelectorAll('.seccion').forEach(x=>x.classList.remove('activa'));b.classList.add('activa');$(b.dataset.tab).classList.add('activa')}));
$('buscarPez').addEventListener('input',renderPeces);$('filtrarOrigen').addEventListener('change',renderPeces);actualizar();
